[package]
name = "rust-tcp-file-transfer"
version = "0.1.0"
edition = "2021"

[profile.release]
strip = "symbols"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
