[package]
name = "rust-tcp-file-transfer"
version = "0.1.0"
edition = "2021"

[profile.release]
strip = true
opt-level = 3
overflow-checks = true
lto = true

[lints.rust]
unsafe_code = "forbid"

[dependencies]
