name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

     runs-on: ubuntu-latest
     permissions:
         contents: write
     steps:
        - uses: actions/checkout@v3
        - name: Build
          run: cargo build --verbose
        - name: Run tests
          run: cargo test --verbose

        
        - name: Changelog
          id: changelog
          uses: heinrichreimer/github-changelog-generator-action@v2.3
          with:
             token: ${{ secrets.GITHUB_TOKEN }}
          

        - name: Release
          uses: elgohr/Github-Release-Action@v4
          env:
             GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with:
             title: ${{ steps.changelog.outputs.release-id }}
