name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

     runs-on: ubuntu-latest
     permissions:
         contents: write
     steps:
        - uses: actions/checkout@v3
        - name: Build
          run:  cargo build --release

        - name: Run tests
          run: cargo test --verbose

        - name: SHA
          run: echo ${{ github.sha }} > Release.txt

        - name: Release
          uses: softprops/action-gh-release@v0.1.15
          id: tag
          with:
             body_path: Release.txt
             generate_release_notes: true
             files: target/release/rust-tcp-file-transfer
        
        
         
