name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:

  build:

     runs-on: ubuntu-latest
     permissions:
         contents: write
     steps:
        - uses: actions/checkout@v3
        - name: Build
          run: cargo build --verbose
        - name: Run tests
          run: cargo test --verbose

        - name: Conventional
          id: version
          uses: TriPSs/conventional-changelog-action@v4
          with:
             github-token: ${{ secrets.GITHUB_TOKEN }}

        - name: Release
          id: release_id
          uses: elgohr/Github-Release-Action@v4
          env:
             GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with:
             title: 0.0.1
