name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --release --verbose
    - name: Run tests
      run: cargo test --verbose
  changelog:
     permissions:
        contents: write
     runs-on: ubuntu-latest
     steps:
      - uses: actions/checkout@v3
      - name: Conventional
        id: changelog
        uses: TriPSs/conventional-changelog-action@v4
        with:
           github-token: ${{ secrets.CHANGELOG_RELEASE }}
      - name: Release
      - uses: actions/create-release@v1
        if: ${{ steps.changelog.outputs.skipped == 'false' }}
        env:
           GITHUB_TOKEN: ${{ secrets.CHANGELOG_RELEASE }}
        with:
           tag_name: ${{ steps.changelog.outputs.tag }}
           release_name: ${{ steps.changelog.outputs.tag }}
           body: ${{ steps.changelog.outputs.clean_changelog }}
