name: Rust Release
on: 
   push: 
      branches: [ "main" ]
jobs:
   Download_then_Release:
      runs-on: ubuntu-latest
      permissions: 
         contents: write
      steps:

         - uses: actions/checkout@v3
         - name: Forge a Folder
           run: mkdir Downloads
           working-directory: /home/runner/work/rust-tcp-file-transfer/rust-tcp-file-transfer/

         - uses: actions/download-artifact@v3
           name: Download
           with:
              path: Downloads/
         
         - uses: actions/checkout@v3
         - name: Display Downloads
           run: ls -R
           working-directory: Downloads
