name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

     runs-on: ubuntu-latest
     permissions:
         contents: write
     steps:
        - uses: actions/checkout@v3
        - name: Build
          run:  cargo build --release

        - name: Run tests
          run: cargo test --verbose

        - name: Delete Old Release
          uses: liudonghua123/delete-release-action@v1
          with:
             release_name: 'Release'

        - name: Release
          uses: softprops/action-gh-release@v0.1.15
          with:
             tag_name: Release
             generate_release_notes: true
             files: target/release/rust-tcp-file-transfer
        
        
        
        
         
