name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:

  build:

     runs-on: ubuntu-latest
     permissions:
         contents: write
     steps:
        - uses: actions/checkout@v3
        - name: Build
          run: cargo build --verbose
        - name: Run tests
          run: cargo test --verbose

        - name: Conventional
          id: changelog
          uses: TriPSs/conventional-changelog-action@v4
          with:
             GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        - name: Release
          id: release
          uses: actions/create-release@v1
          env:
             GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with:
             tag_name: ${{ steps.build.outputs.tag }}
             release_name: ${{ github.event.release.tag_name }}
             body: ${{ steps.release.outputs.clean_changelog }}


