name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

     runs-on: ubuntu-latest
     permissions:
         contents: write
     steps:
        - uses: actions/checkout@v3
        - name: Build
          run: 
             cargo build --release
             chmod +x target/release/rust-tcp-file-transfer
        - name: Run tests
          run: cargo test --verbose
         
        - name: Changelog
          uses: ardalanamini/auto-changelog@v4
          id  : changelog
          with:
             github-token: ${{ github.token }}
             release-name: v0.0.1

        - name: Release
          uses: softprops/action-gh-release@v0.1.15
          id: tag
          with:
             tag_name: Release
        - uses: actions/upload-artifact@v3
          with:
             name: rust-tcp-transfer
             path: target/release/rust-tcp-file-transfer
        
         
