name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

     runs-on: ubuntu-latest
     permissions:
         contents: write
     steps:
        - uses: actions/checkout@v3
        - name: Build
          run: cargo build --verbose
        - name: Run tests
          run: cargo test --verbose
         
        - name: Changelog
          uses: thomaseizinger/keep-a-changelog-new-release@v1
          with:
             tag: ${{ github.event.inputs.version }}
        
        - name: Release
          uses: docker://antonyurchenko/git-release:latest
          env:
             GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with:
             args: |
                darwin-amd64.zip
                linux-amd64.zip
                windows-amd64.zip
