name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

     runs-on: ubuntu-latest
     permissions:
         contents: write
     steps:
        - uses: actions/checkout@v3
        - name: Build
          run: cargo build --verbose
        - name: Run tests
          run: cargo test --verbose

        
        - name: Changelog
          uses: ardalanamini/auto-changelog@v4
          id  : changelog
          with:
             github-token            : ${{ github.token }}
             commit-types            : |
                feat: New Features
                fix: Bug Fixes
                build: Build System & Dependencies
                perf: Performance Improvements
                docs: Documentation
                test: Tests
                refactor: Refactors
                chore: Chores
                ci: CI
                style: Code Style
                revert: Reverts
             default-commit-type     : Other Changes
             release-name            : v1.0.0
             release-name-prefix     : ""
             mention-authors         : true
             mention-new-contributors: true
             include-compare-link    : true
             include-pr-links        : true
             include-commit-links    : true
             semver                  : true
             use-github-autolink     : true

        - name: Release
          id: release_id
          uses: elgohr/Github-Release-Action@v4
          env:
             GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with:
             title: ${{ steps.changelog.outputs.release-id }}
